// src/gameData/careers/generalCareers.js

const generalCareers = [
  {
    id: 'car-abetare',
    name: 'Arbetare',
    type: 'general',
    description: '',
    characteristicRolls: ['VIL', 'TÅL', 'RÖR'],
    baseCareerSkillPoints: [5,10,15],
    baseFreeSkillPoints: [15,20,25],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: ['Arbetare', 'Förman', 'Arbetsledare', 'Verksmästare'],
    startingCapital: [50, 100, 500],
    eventTable: 'arbetareCareerEvents',
    associatedSkills: ['Elektronik', 'Fingerfärdighet', 'Klättra', 'Mekanik', 'Köra/truck', 'Köra/lastbil'],
    restrictions: [], // No general restrictions for this one
    yearsInCareer: '1T6+2',
  },
  {
    id: 'car-artist',
    name: 'Artist',
    type: 'general',
    description: 'Skådespelare, musiker eller programledare.',
    characteristicRolls: ['PER', 'Mediastatus', 'Agera'],
    baseCareerSkillPoints: [15, 20, 25],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: 'Skådespelare',
    startingCapital: [50, 200, 10000],
    eventTable: 'artistCareerEvents',
    associatedSkills: ['Agera', 'Dans', 'Förklädnad', 'Media', 'Sjunga', 'Språk', 'Stil & smak', 'Övertalning'],
    // restrictions: [{ type: 'min_attribute', attribute: 'Bildning', value: 8 }],
    yearsInCareer: '1T6',
  },
  {
    id: 'car-affarsman',
    name: 'Affärsman',
    type: 'general',
    description: 'Jobbar med egen firma, troligen som underleverantör eller konsult åt ett större företag.',
    characteristicRolls: ['PSY', 'Ekonomi', 'Startkapital'],
    baseCareerSkillPoints: [15, 20, 25],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: 'Pathfinder',
    startingCapital: [50, 100, 5000],
    eventTable: 'affarsmanCareerEvents',
    associatedSkills: ['Administration', 'Ekonomi', 'Juridik', 'Ledarskap', 'Media', 'Psykologi', 'Socialt Uppträdande', 'Värdering', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6+1',
  },
  {
    id: 'car-foretagsman',
    name: 'Företagsman',
    type: 'general',
    description: 'Jobbar på megaföretag.',
    characteristicRolls: ['PSY', 'Ekonomi', 'Examen'],
    baseCareerSkillPoints: [15, 25, 40],
    baseFreeSkillPoints: [10, 10, 10],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: 'Pathfinder',
    startingCapital: [200, 1000, 5000],
    eventTable: 'foretagsmanCareerEvents',
    associatedSkills: ['Administration', 'Diplomati', 'Ekonomi', 'Informationssökning', 'Juridik', 'Ledarskap', 'Psykologi', 'Socialt Uppträdande', 'Stil & smak', 'Värdering', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6+1',
  },
  {
    id: 'car-gangster',
    name: 'Gangster',
    type: 'general',
    description: 'Medlem av den organiserade brottsligheten.',
    characteristicRolls: ['PSY', 'PER', 'Undre världen'],
    baseCareerSkillPoints: [15, 20, 25],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [2, 3, 4],
    promotion: 'Pathfinder',
    startingCapital: [100, 500, 2500],
    eventTable: 'gangsterCareerEvents',
    associatedSkills: ['Ekonomi', 'Förhörsteknik', 'Hasardspel', 'Juridik', 'Köra/bil', 'Ledarskap', 'Närstrid/Slagsmål', 'Närstrid/Kniv', 'Pistol', 'Undre världen', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6+1',
  },
  {
    id: 'car-gangmedlem',
    name: 'Gängmedlem',
    type: 'general',
    description: 'Medlem av ett gatugäng.',
    characteristicRolls: ['PSY', 'PER', 'Undre världen'],
    baseCareerSkillPoints: [10, 15, 20],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [2, 3, 4],
    promotion: 'Pathfinder',
    startingCapital: [5, 10, 50],
    eventTable: 'gangmedlemCareerEvents',
    associatedSkills: ['Fingerfärdighet', 'Genomsöka', 'Köra/bil', 'Närstrid/Slagsmål', 'Närstrid/Kniv', 'Pistol', 'Supa', 'Undre världen', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6',
  },
  {
    id: 'car-hacker',
    name: 'Hacker',
    type: 'general',
    description: 'IT-Proffs på nätet.',
    characteristicRolls: ['PSY', 'Hacking', 'Informationssökning'],
    baseCareerSkillPoints: [20, 25, 30],
    baseFreeSkillPoints: [5, 10, 15],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: 'Pathfinder',
    startingCapital: [20, 250, 5000],
    eventTable: 'hackerCareerEvents',
    associatedSkills: ['Fingerfärdighet', 'Genomsöka', 'Köra/bil', 'Närstrid/Slagsmål', 'Närstrid/Kniv', 'Pistol', 'Supa', 'Undre världen', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6',
  },
  {
    id: 'car-kriminell',
    name: 'Kriminell',
    type: 'general',
    description: 'Försörjer sig på småbrottslighet.',
    characteristicRolls: ['PSY', 'Cool', 'Undre världen'],
    baseCareerSkillPoints: [15, 20, 25],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [0, 2, 3],
    promotion: 'Pathfinder',
    startingCapital: [10, 200, 5000],
    eventTable: 'kriminellCareerEvents',
    associatedSkills: ['Dyrka lås', 'Fingerfärdighet', 'Förfalskning', 'Gömma', 'Klättra', 'Köra/bil', 'Närstrid/Kniv', 'Pistol', 'Smyga', 'Spaning', 'Sprängteknik', 'Säkerhetssystem', 'Värdering', 'Undre världen', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6',
  },
    {
    id: 'car-mediaarbetare',
    name: 'Mediaarbetare',
    type: 'general',
    description: 'Reporter eller programledare.',
    characteristicRolls: ['PER', 'Media', 'Informationssökning'],
    baseCareerSkillPoints: [15, 20, 25],
    baseFreeSkillPoints: [10, 15, 20],
    baseStridsvanaPoints: [0, 0, 0],
    promotion: 'Pathfinder',
    startingCapital: [50, 500, 1000],
    eventTable: 'mediaarbetareCareerEvents',
    associatedSkills: ['Agera', 'Foto & film', 'Förhörsteknik', 'Informationssökning', 'Media', 'Skriva/läsa', 'Socialt uppträdande', 'Språk', 'Stil & smak', 'Övertalning' ],
    restrictions: [],
    yearsInCareer: '1T6',
  },

];

export default generalCareers;