const skillsData = [
  { name: 'Administration', value: 0, easy: false, buyable: false }, // <-- Added buyable: false
  { name: 'Första hjälpen', value: 0, easy: false, buyable: false },
  { name: 'Köra fartyg', value: 0, easy: false, buyable: false },
  { name: 'Sjunga', value: 0, easy: false, buyable: false },
  { name: 'Agera', value: 0, easy: false, buyable: false },
  { name: 'Genomsöka', value: 0, easy: false, buyable: false },
  { name: 'Köra lastbil', value: 0, easy: false, buyable: false },
  { name: 'Skidåkning', value: 0, easy: false, buyable: false },
  { name: 'Akrobatik', value: 0, easy: false, buyable: false },
  { name: 'Genteknik', value: 0, easy: false, buyable: false },
  { name: 'Köra motorcykel', value: 0, easy: false, buyable: false },
  { name: 'Skriva/Läsa', value: 0, easy: false, buyable: false },
  { name: 'Antropologi', value: 0, easy: false, buyable: false },
  { name: 'Geografi', value: 0, easy: false, buyable: false },
  { name: 'Köra svävare', value: 0, easy: false, buyable: false },
  { name: 'Smyga', value: 0, easy: false, buyable: false },
  { name: 'Armborst', value: 0, easy: false, buyable: false },
  { name: 'Geologi', value: 0, easy: false, buyable: false },
  { name: 'Ledarskap', value: 0, easy: false, buyable: false },
  { name: 'Socialt uppträdande', value: 0, easy: false, buyable: false },
  { name: 'Astronomi', value: 0, easy: false, buyable: false },
  { name: 'Gevär', value: 0, easy: false, buyable: false },
  { name: 'Lingvistik', value: 0, easy: false, buyable: false },
  { name: 'Sociologi', value: 0, easy: false, buyable: false },
  { name: 'Automateld', value: 0, easy: false, buyable: false },
  { name: 'Granatkastare', value: 0, easy: false, buyable: false },
  { name: 'Manövrera stridsrustning', value: 0, easy: false, buyable: false },
  { name: 'Spaning', value: 0, easy: false, buyable: false },
  { name: 'Biologi', value: 0, easy: false, buyable: false },
  { name: 'Gömma', value: 0, easy: false, buyable: false },
  { name: 'Matematik', value: 0, easy: false, buyable: false },
  { name: 'Sprängteknik', value: 0, easy: false, buyable: false },
  { name: 'Båge', value: 0, easy: false, buyable: false },
  { name: 'Hacking', value: 0, easy: false, buyable: false },
  { name: 'Matlagning', value: 0, easy: false, buyable: false },
  { name: 'Spåra', value: 0, easy: false, buyable: false },
  { name: 'Cybernetik', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Bokbinderi', value: 0, easy: false, buyable: false },
  { name: 'Media', value: 0, easy: false, buyable: false },
  { name: 'Stil & smak', value: 0, easy: false, buyable: false },
  { name: 'Dans', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Metallsmide', value: 0, easy: false, buyable: false },
  { name: 'Medicin', value: 0, easy: false, buyable: false },
  { name: 'Strategi', value: 0, easy: false, buyable: false },
  { name: 'Datateknik', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Måleri', value: 0, easy: false, buyable: false },
  { name: 'Mekanik', value: 0, easy: false, buyable: false },
  { name: 'Stridsvana', value: 0, easy: false, buyable: false },
  { name: 'Design', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Skomakeri', value: 0, easy: false, buyable: false },
  { name: 'Musik', value: 0, easy: false, buyable: false },
  { name: 'Supa', value: 0, easy: false, buyable: false },
  { name: 'Diplomati', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Skrädderi', value: 0, easy: false, buyable: false },
  { name: 'Navigering', value: 0, easy: false, buyable: false },
  { name: 'Säkerhetssystem', value: 0, easy: false, buyable: false },
  { name: 'Dra vapen', value: 0, easy: false, buyable: false },
  { name: 'Hantverk-Skulptering', value: 0, easy: false, buyable: false },
  { name: 'Närstrid-Klor', value: 0, easy: false, buyable: false },
  { name: 'Taktik', value: 0, easy: false, buyable: false },
  { name: 'Dykning', value: 0, easy: false, buyable: false },
  { name: 'Hasardspel', value: 0, easy: false, buyable: false },
  { name: 'Närstrid–Kniv', value: 0, easy: false, buyable: false },
  { name: 'Undervisning', value: 0, easy: false, buyable: false },
  { name: 'Dyrka lås', value: 0, easy: false, buyable: false },
  { name: 'Historia', value: 0, easy: false, buyable: false },
  { name: 'Närstrid–Slagsmål', value: 0, easy: false, buyable: false },
  { name: 'Undre världen', value: 0, easy: false, buyable: false },
  { name: 'Ekonomi', value: 0, easy: false, buyable: false },
  { name: 'Hoppa', value: 0, easy: false, buyable: false },
  { name: 'Närstrid-Obeväpnad', value: 0, easy: false, buyable: false },
  { name: 'Värdering', value: 0, easy: false, buyable: false },
  { name: 'Eldkastare', value: 0, easy: false, buyable: false },
  { name: 'Informationssök.', value: 0, easy: false, buyable: false },
  { name: 'Pilot-flygplan', value: 0, easy: false, buyable: false },
  { name: 'Överlevnad', value: 0, easy: false, buyable: false },
  { name: 'Eldledning', value: 0, easy: false, buyable: false },
  { name: 'Jakt', value: 0, easy: false, buyable: false },
  { name: 'Pilot-helikopter', value: 0, easy: false, buyable: false },
  { name: 'Övertalning', value: 0, easy: false, buyable: false },
  { name: 'Elektronik', value: 0, easy: false, buyable: false },
  { name: 'Juridik', value: 0, easy: false, buyable: false },
  { name: 'Pilot-rymd', value: 0, easy: false, buyable: false },
  { name: 'Filosofi', value: 0, easy: false, buyable: false },
  { name: 'Kasta', value: 0, easy: false, buyable: false },
  { name: 'Pistol', value: 0, easy: false, buyable: false },
  { name: 'Fingerfärdighet', value: 0, easy: false, buyable: false },
  { name: 'Kastkniv', value: 0, easy: false, buyable: false },
  { name: 'Politik', value: 0, easy: false, buyable: false },
  { name: 'Foto & Film', value: 0, easy: false, buyable: false },
  { name: 'Kemi', value: 0, easy: false, buyable: false },
  { name: 'Programmering', value: 0, easy: false, buyable: false },
  { name: 'Fritt Fall', value: 0, easy: false, buyable: false },
  { name: 'Kirurgi', value: 0, easy: false, buyable: false },
  { name: 'Psykologi', value: 0, easy: false, buyable: false },
  { name: 'Fysik', value: 0, easy: false, buyable: false },
  { name: 'Klättra', value: 0, easy: false, buyable: false },
  { name: 'Rekylfria vapen', value: 0, easy: false, buyable: false },
  { name: 'Förfalskning', value: 0, easy: false, buyable: false },
  { name: 'Konstkännedom', value: 0, easy: false, buyable: false },
  { name: 'Religion', value: 0, easy: false, buyable: false },
  { name: 'Förföra', value: 0, easy: false, buyable: false },
  { name: 'Köra bandvagn', value: 0, easy: false, buyable: false },
  { name: 'Rymddräkt', value: 0, easy: false, buyable: false },
  { name: 'Förhörsteknik', value: 0, easy: false, buyable: false },
  { name: 'Köra bil', value: 0, easy: false, buyable: false },
  { name: 'Samband', value: 0, easy: false, buyable: false },
  { name: 'Förklädnad', value: 0, easy: false, buyable: false },
  { name: 'Köra båt', value: 0, easy: false, buyable: false },
  { name: 'Simma', value: 0, easy: false, buyable: false },
];

export default skillsData;