// Each object represents a range, and the event description for that range

export const advantagesEvents = [
  { min: 1, max: 1, description: "Alkoholtålighet. Färdigheten Supa är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Supa' }] },
  { min: 2, max: 2, description: "Alkoholtolerant. Rollpersonen blir sällan speciellt påverkad av alkohol. Alla slag där färdigheten Supa används blir en nivå enklare (−Ob1T6)." },
  { min: 3, max: 3, description: "Allmänbildad. Rollpersonen får höjd BIL med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Bildning' }] },
  { min: 4, max: 4, description: "Ambidextriös. Rollpersonen är 'dubbelhänt' och kan använda båda händerna samtidigt. Rollpersonen drabbas alltså inte av någon ökad svårighet när man använder 'fel' hand." },
  { min: 5, max: 5, description: "Andra chansen. En gång per spelmöte kan spelaren få slå om ett svårighetsslag, vilket som helst. Om det slås om måste det nya resultatet användas. Kan inte användas då rollpersonen skapas eller för förbättringsslag." },
  { min: 6, max: 6, description: "Blixtrande reflexer. Färdigheten Dra vapen är lättlärd. Dessutom modifieras rollpersonens turordning med en fast modifikation på tio (+10).",  modifiers: [{type: 'lattlard', skill: 'Dra Vapen' }, {type: 'secondary_attribute', name: 'Turordning', value: 10 }] },
  { min: 7, max: 7, description: "Bollsinne. Har lätthet för att kasta och ta emot. Färdigheten Kasta är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Kasta' }] },
  { min: 8, max: 8, description: "Bra hörsel. Höj HÖR med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Hörsel' }] },
  { min: 9, max: 9, description: "Byggd som en oxe. Öka rollpersonens STY med tre (+3). Dessutom ökar rollpersonens kroppsbryggnad en nivå (alltid minst 'Normal' och högst 'Massiv').", modifiers: [{type: 'attribute', amount: 3, target: 'Styrka' }]  },
  { min: 10, max: 10, description: "Charmroll. Färdigheten Förföra är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Förföra' }] },
  { min: 11, max: 11, description: "Chockresistent. Rollpersonen tål chocker bättre än andra människor. Chockslag blir alltid en nivå enklare (−Ob1T6)." },
  { min: 12, max: 12, description: "Dansare. Färdigheten Dans är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Dansa' }] },
  { min: 13, max: 13, description: "Ekonomiskt geni. Färdigheten Ekonomi är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Ekonomi' }]  },
  { min: 14, max: 14, description: "Elektronikgeni. Färdigheten Elektronik är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Elektronik' }]  },
  { min: 15, max: 15, description: "Empatisk. Rollpersonen har lätt att förstå andras känslor och sätta sig in i andras situationer. Färdigheterna Övertalning och Diplomati är lättlärda.", modifiers: [{type: 'lattlard', skill: 'Övertala' }, {type: 'lattlard', skill: 'Diplomati' }] },
  { min: 16, max: 16, description: "Extrovert människa. Färdigheten Socialt uppträdande är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Socialt Uppträdande' }] },
  { min: 17, max: 17, description: "Extermt fingerfärdig. Färdigheten Fingferfärdighet är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Fingerfärdighet' }]  },
  { min: 18, max: 18, description: "Fisker i vatten. Färdigheterna Simma och Dykning är lättlärda. 1", modifiers: [{type: 'lattlard', skill: 'Simma' }, {type: 'lattlard', skill: 'Dykning' } ] },
  { min: 19, max: 19, description: "Flyfotad. Förflyttningen ökar med två (+2) meter per runda.",  modifiers: [{type: 'secondary_attribute', name: 'Förflyttning', value: 2 }] },
  { min: 20, max: 20, description: "Fotografiskt minne. Rollpersonen har förmågan att komma ihåg bilder exakt." },
  { min: 21, max: 21, description: "Frisk. Rollpersonen får alltid en nivå enklare (−Ob1T6) på alla slag mot TÅL för att motstå sjukdomar." },
  { min: 22, max: 22, description: "Friskt blod. Rollpersonen får en extra kolumn Blodförlust i Skadesektionen (dock inte fler än 10 kolumner)." },
  { min: 23, max: 23, description: "Född gymnast. Färdigheten Akrobatik och Hoppa är lättlärda.", modifiers: [{type: 'lattlard', skill: 'Akrobatik' }, {type: 'lattlard', skill: 'Hoppa' }] },
  { min: 24, max: 24, description: "Född lärare. Färdigheten Undervisning är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Undervisning' }] },
  { min: 25, max: 25, description: "Född pilot. Färdigheten Pilot-helikopter är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Pilot' }] },
  { min: 26, max: 26, description: "Född spelare. Färdigheten Hasardspel är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Hasardspel' }] },
  { min: 27, max: 27, description: "Författare. Färdigheten Skriva/läsa är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Skriva/Läsa' }] },
  { min: 28, max: 28, description: "Förförarexpert. Färdigheten Förföra är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Förföra' }] },
  { min: 29, max: 29, description: "Förklädnadsmästare. Färdigheten Förklädnad är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Förklädnad' }] },
  { min: 30, max: 30, description: "Gifttålig. Rollpersonen får en nivå enklare (−Ob1T6) på alla slag mot TÅL då rollpersonen råkar ut för förgiftningar." },
  { min: 31, max: 31, description: "God syn. Rollpersonen får höja sin SYN med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Syn' }] },
  { min: 32, max: 32, description: "Gott läkekött. Rollpersonen läker Trauma och Smärta dubbelt så fort än de normala." },
  { min: 33, max: 33, description: "Hacker. Färdigheterna Hacking och Programmering är lättlärda.", modifiers: [{type: 'lattlard', skill: 'Hacking' }, {type: 'lattlard', skill: 'Programmering' } ] },
  { min: 34, max: 34, description: "Harmonisk. Rollpersonens psykostålighet ökar med en kolumn (dock högst 10 kolumner)." },
  { min: 35, max: 35, description: "Helare. Färdigheten Första hjälpen är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Första Hjälpen' }]},
  { min: 36, max: 36, description: "Idrottare. Färdigheten Idrott är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Idrott' }] },
  { min: 37, max: 37, description: "Intelligent. Rollpersonen får höja sin PSY med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Psyke' }] },
  { min: 38, max: 38, description: "Jaktinstinkt. Färdigheten Jakt är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Jakt' }] },
  { min: 39, max: 39, description: "Kan ignorera smärta. Svårighetsökningen som rollpersonen får från sin eventuella Smärta på grund av skada minskar med två nivåer (−Ob2T6)." },
  { min: 40, max: 40, description: "Karismatisk. Rollpersonen får en höjning i PER med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Personlighet' }] },
  { min: 41, max: 41, description: "Klättrare. Färdigheten Klättra är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Kasta' }] },
  { min: 42, max: 42, description: "Knivkastarexpert. Färdigheten Kastkniv är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Kastkniv' }] },
  { min: 43, max: 43, description: "Konstnärssjäl. Färdigheterna Konstnämend och Design är lättlärda. 1", modifiers: [{type: 'lattlard', skill: 'Konstkännedom' }, {type: 'lattlard', skill: 'Design' }] },
  { min: 44, max: 44, description: "Kylig. Rollpersonens Cool höjs med två (+2). Detta kan även medföra att Turordningen behöver räknas om.", modifiers: [{type: 'secondary_attribute', name: 'Cool', value: 2}]  },
  { min: 45, max: 45, description: "Gourmet. Färdigheten Matlagning är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Matlagning' }]  },
  { min: 46, max: 46, description: "Lungstark. Rollpersonen har alltid en nivå enklare (−Ob1T6) att hålla andan och överleva besvärliga luftförhållanden." },
  { min: 47, max: 47, description: "Lär sig snabbt vid undervisning. Halvera alla träningstider vid undervisning och studier." },
  { min: 48, max: 48, description: "Matematiskt snille. Färdigheten Matematik är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Matematik' }]  },
  { min: 49, max: 49, description: "Mental balans. Blås ej mot rollpersonens Mentalvärde är alltid en nivå enklare (−Ob1T6)." },
  { min: 50, max: 50, description: "Modelejon. Färdigheten Stil & Smak är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Stil & smak' }]  },
  { min: 51, max: 51, description: "Motståndskraftig. Rollpersonen får en extra skadekolumn och en extra utmattningskolumn höjs med ett led (dock aldrig mer än tio kolumner)." },
  { min: 52, max: 52, description: "Musikaliskt geni. Färdigheten Musik är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Musik' }]  },
  { min: 53, max: 53, description: "Mycket härdad. Rollpersonen får en extra kolumn på Smärta och Trauma på sin skadetålighet (dock aldrig mer än tio kolumner)." },
  { min: 54, max: 54, description: "Mycket stadig på handen. Öka räckvidden med alla avstånds- och skyltvapen med 20%. Avrunda nedåt till närmaste fem meter." },
  { min: 55, max: 55, description: "Nattseende. Rollpersonen ser hyfsat bra även i svagt ljus (ignorera modifikationer på grund av svagt ljus). Rollpersonen kan dock inte se i totalt kolmörker." },
  { min: 56, max: 56, description: "Nattuggla. Rollpersonen har ett onaturligt litet behov av sömn. Det räcker som regel med fyra timmars sömn per dygn för att rollpersonen skall vara utvilad." },
  { min: 57, max: 57, description: "Naturlig bilförare. Färdigheten Köra: bil är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Köra Bil' }] },
  { min: 58, max: 58, description: "Naturlig fotograf. Färdigheten Foto & film är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Foto & Film' }] },
  { min: 59, max: 59, description: "Naturlig ledare. Färdigheten Ledarskap är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Ledarskap' }] },
  { min: 60, max: 60, description: "Naturlig skytt. Färdigheterna Pistol och Gevär är lättlärda. 1", modifiers: [{type: 'lattlard', skill: 'Pistol' }, {type: 'lattlard', skill: 'Gevär' }] },
  { min: 61, max: 61, description: "Observant. Färdigheterna Spaning och Genomsöka är lättlärda. 1", modifiers: [{type: 'lattlard', skill: 'Spaning' }, {type: 'lattlard', skill: 'Genomsöka' }] },
  { min: 62, max: 62, description: "Ormtunga. Rollpersonen har ett vältränat lögncentrum i hjärnan. Rollpersonen får alltid en nivå enklare (−Ob1T6) att ljuga (då färdigheten Övertalning används)." },
  { min: 63, max: 63, description: "Outtröttlig. Rollpersonen får två extra utmattningskolumner i utmattningssektionen (dock aldrig fler än tio kolumner)." },
  { min: 64, max: 64, description: "Packåsna. Rollpersonen orkar bära betydligt mer än gemene man. Bärförmåga är lika med (STY+TÅL)." },
  { min: 65, max: 65, description: "Pedagog. Färdigheten Undervisning är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Undervisning' }] },
  { min: 66, max: 66, description: "Perfekt tidskänsla. Rollpersonen behöver ingen klocka utan kan alltid avgöra vad klockan är. Rollpersonen kommer alltid precis i tid." },
  { min: 67, max: 67, description: "Reflexsnabb. Rollpersonens turordning modifieras med en fast modifikation på fem (+5).",  modifiers: [{type: 'secondary_attribute', name: 'Turordning', value: 5}] },
  { min: 68, max: 68, description: "Rollpersonen besitter ett specialintresse. En valfri kunskapsfärdighet (ej Expertfärdigheter) är lättlärd." },
  { min: 69, max: 69, description: "Rollpersonen gillar helikoptrar. Färdigheten Pilot:helikopter är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Pilot' }] },
  { min: 70, max: 70, description: "Rymdmänniska. Färdigheten Fritt fall är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Fritt Fall' }]  },
  { min: 71, max: 71, description: "Råstark. Rollpersonen vet hur man åsankrar skada på omgivningen. Öka rollpersonens skadevärden med +Ob1T6 när rollpersonen använder färdigheten Närstrid:slagmål." },
  { min: 72, max: 72, description: "Seglivad. Rollpersonen får en nivå enklare (−Ob1T6) på alla Dödsslag." },
  { min: 73, max: 73, description: "Sinne för värdering. Färdigheten Värdering är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Värdera' }] },
  { min: 74, max: 74, description: "Skadetålig. Rollpersonen får en extra kolumn på Trauma under Skadesektionen (dock inte fler än 10 kolumner)." },
  { min: 75, max: 75, description: "Skådespelare. Färdigheten Agera är lättlärd", modifiers: [{type: 'lattlard', skill: 'Agera' }] },
  { min: 76, max: 76, description: "Slagskämpe. Färdigheten Närstrid:Slagsmål är lättlärd", modifiers: [{type: 'lattlard', skill: 'Närstrid' }] },
  { min: 77, max: 77, description: "Smidig. Rollpersonen får höja sin RÖR med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Rörlighet' }] },
  { min: 78, max: 78, description: "Smygare. Färdigheten Smyga är lättlärd. 1", modifiers: [{type: 'lattlard', skill: 'Smyga' }]   },
  { min: 79, max: 79, description: "Smärtokänslig. Rollpersonen får automatisk 10 kolumner Smärta i Skadetålig-kolumnen." },
  { min: 80, max: 80, description: "Smärttålilg. Rollpersonen får en extra kolumn på Smärta under Skadesektionen (dock inte fler än 10 kolumner)." },
  { min: 81, max: 81, description: "Sover lätt. Rollpersonen har alltid en nivå enklare att vakna när hen sover." },
  { min: 82, max: 82, description: "Språkgeni. Förbättringsslag för samtliga språkfärdigheter är en nivå enklare (+Ob1T6)" },
  { min: 83, max: 83, description: "Sprängexpert. Rollpersonen är fascinerad av explosioner. Färdigheten Sprängteknik är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Sprängteknik' }] },
  { min: 84, max: 84, description: "Stark överlevnadsinstinkt. Rollpersonen kan utföra responshandlingen Försvara sig en nivå enklare (-Ob1T6)." },
  { min: 85, max: 85, description: "Stark. Rollpersonen får höja sin STY med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Styrka' }] },
  { min: 86, max: 86, description: "Stigfinnare. Färdigheten Spåra är lättlärd",  modifiers: [{type: 'lattlard', skill: 'Spåra' }]},
  { min: 87, max: 87, description: "Strålande Ögon. Alla slag mot färdigheten Övertala är en enivå enklare (-Ob1T6) under förutsättningar att Rollpersonen har ögonkontakt." },
  { min: 88, max: 88, description: "Stålnäve. Rollpersonen gör Ob2T6 extra i skada när hen angriper någon med enbart nävarna. Gäller alla närstridsfärdigheter så länge skadan kommer från händerna." },
  { min: 89, max: 89, description: "Synsk. Rollpersonen har förmågan att då och då få en 'minnesbild' av något som kommer att hända. Spelledaren bestämmer när och var detta händer." },
  { min: 90, max: 90, description: "Sångfågel. Färdigheten Sjunga är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Sjunga' }] },
  { min: 91, max: 91, description: "Taktiskt Geni. Färdigheterna Taktik och Strategi är lättlärda.", modifiers: [{type: 'lattlard', skill: 'Strategi' }, {type: 'lattlard', skill: 'Taktik' }] },
  { min: 92, max: 92, description: "Tursam. Öka rollpersonens Tur med +1T6.", modifiers: [{type: 'secondary_attribute', name: 'Tur', value: "1T6" }] },
  { min: 93, max: 93, description: "Tålig. Höj TÅL med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Tålighet' }] },
  { min: 94, max: 94, description: "Uppmärksam. Höj både SYN och HÖR med två (+2)", modifiers: [{type: 'attribute', amount: 2, target: 'Hörsel' }, {type: 'attribute', amount: '2', target: 'Syn' }] },
  { min: 95, max: 95, description: "Vacker. Höj PER med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Personlighet' }]  },
  { min: 96, max: 96, description: "Viljestark. Höj VIL med två (+2).", modifiers: [{type: 'attribute', amount: 2, target: 'Vilja' }]  },
  { min: 97, max: 97, description: "Lättlärd. Valfri färdighet är lättlärd." },
  { min: 98, max: 98, description: "Överlevnadskonstnär. Färdigheten Överlevnad är lättlärd.", modifiers: [{type: 'lattlard', skill: 'Överlevnad' }]  },
  { min: 99, max: 100, description: "Slå två gånger på denna tabell och använd båda resultaten." },
]

export const disadvantagesEvents = [
  { min: 1, max: 1, description: "Albino: Rollpersonen har kritvit hud, rödaktiga ögon och är mycket känslig för solljus. Var 15:e minut som huden är utsatt för starkt solsken får rollpersonen Ob1T6 poäng Smärta. Denna försvinner om rollpersonen får vila minst ett dygn. Vid starkt solljus for rollpersonen en nivå svårare vid alla slag där synen används." },
  { min: 2, max: 3, description: "Allergisk: Rollpersonen är allergisk mot något vanligt ämne som damm, pollen eller nickel. Om rollpersonen är i närheten eller rör vid det hen är allergisk mot mer än 5 min känner sig rollpersonen dålig och får en nivå svårare på allt hen tar sig för. Droger som hämmar allergin finns och fungerar precis som Seredon (se droger)." },
  { min: 4, max: 4, description: "Allvarlig sjukdom: Rollpersonen lider av en permanent sjukdom som kräver medicinering. Medicinen kostar 150 euro i månaden." },
  { min: 5, max: 5, description: "Ansiktsförlamning: Ena sidan av rollpersonens ansikte är förlamat. Rollpersonen har svårt att stänga ögonlocken och hålla munnen stängd på den sidan. Plastikkirurgi kan åtgärda detta.", modifiers: [{type: 'attribute', target: 'Personlighet', amount: -1 }] },
  { min: 6, max: 6, description: "Blödarsjuka: Rollpersonen slutar inte blöda av sig själv och måste behandlas snabbt vid skador. Det tar en timme för varje poäng blödningstakt att återhämta sig. Kan enbart drabba män." },
  { min: 7, max: 7, description: "Cyberresistent: Kroppen stöter bort cybernetiska implantat med hög risk. Varje gång rollpersonen installerar cybertech måste hen slå ett normalsvårt slag (Ob3T6) under TÅL för att kroppen inte skall stöta bort det. Om det händer blir rollpersonen sängliggande i Ob2T6 dagar och måste operera bort tillägget. Psykoskryssen kvarstår." },
  { min: 8, max: 9, description: "Darrhänt: Rollpersonen har svårt med finmotorik och precision. Får en nivå svårare på allt som involverar precision, t.ex. prickskytte, Fingerfärdighet och spela instrument." },
  { min: 10, max: 10, description: "Disträ: Rollpersonen har svårt att koncentrera sig i stressade situationer och får därför en nivå svårare på Spaning, SYN, HÖR och VIL vid stressaade situationer." },
  { min: 11, max: 11, description: "Djurfientlig: Djur reagerar negativt på rollpersonens närvaro. Rollpersonen kan aldrig bli vän med djur oavsett hur hen agerar." },
  { min: 12, max: 12, description: "Dålig andedräkt: Rollpersonen får en nivå svårare på allt i sociala situationer om andedräkten inte åtgärdas med t.ex. munspray." },
  { min: 13, max: 14, description: "Dålig hand med barn: Rollpersonen har svårt att relatera till barn. Rollpersonen har två nivåer svårare mot Övertala när den används mot barn." },
  { min: 15, max: 16, description: "Dålig lögnare: Rollpersonen har mycket svårt att ljuga övertygande. Två nivåer svårare varje gång rollpersonen försöker tala osanning." },
  { min: 17, max: 17, description: "Extremt blyg: Rollpersonen får panik eller svårigheter att tala med okända, särskilt det motsatta könet. All kommunikation med okända personer är en nivå svårare. Förföra är två nivåer svårare." },
  { min: 18, max: 18, description: "Extremt ädel: Rollpersonen kan inte attackera obeväpnade eller använda fula knep. Om så skulle ske får rollpersonen Ob1T6 psykoskryss vid varje tillfälle." },
  { min: 19, max: 19, description: "Feg: Rollpersonen tenderar att fly eller gömma sig vid faror. Rollpersonen kan tillfälligt hämta mod genom ett svårt slag (Ob4T6) mot VIL i varje ny situation." },
  { min: 20, max: 21, description: "Fet: Rollpersonen är mycket överviktig, vilket påverkar uthållighet och rörlighet. Minska antalet utmattningskolumner till hälften avrundat uppåt." },
  { min: 22, max: 25, description: "Fobiker: Rollpersonen har en stark fobi och kan få panik vid konfrontation. Svårigheten (slå mot VIL) är i de flesta fall normal men kan vara värre i vissa situationer. SL avgör vad rollpersonen har fobi mot." },
  { min: 26, max: 27, description: "Färgblind: Rollpersonen kan inte se skillnad på färger." },
  { min: 28, max: 29, description: "Födelsemärke: Rollpersonen har ett stort födelsemärke. Slå på träffområdestabellen för att avgöra var det sitter." },
  { min: 30, max: 30, description: "Förtidigt åldrande: Rollpersonen har en sjukdom som åldrar kroppen snabbt. Från och med 20 års ålder måste rollpersonen så två slag per år på åldringstabellen." },
  { min: 31, max: 31, description: "Halt: Rollpersonen rör sig långsammare och har svårare med förflyttning. Förflyttning minskar med 2. Kan givetvis åtgärdas med cybertech." },
  { min: 32, max: 32, description: "Helt orblind: Rollpersonen kan varken lära sig skriva eller läsa." },
  { min: 33, max: 33, description: "Hörselskada: Halvera rollpersonens HÖR." },
  { min: 34, max: 34, description: "Dåligt immunförsvar: Rollpersonen är infektionskänslig och mottaglig för smitta. Alla slag mot TÅL blir två nivåer svårare (+Ob2T6) för att motstå infektioner." },
  { min: 35, max: 35, description: "Impotent. Rollpersonen vill inte ha sex eftersom det kan bli pinsamt eller smärtsamt." },
  { min: 36, max: 36, description: "Ingen orienteringsförmåga: Rollpersonen kan aldrig lära sig färdigheten Navigation och tar dubbelt så lång tid på sig att lära sig Geografi. Går ofta vilse och måste ha någon som visar hen vägen. Kompasser är obegripliga." },
  { min: 37, max: 37, description: "Inget kroppshår. Rollpersonen har inte ett hårstrå någonstans på kroppen." },
  { min: 38, max: 38, description: "Trögtänkt. Rollpersonen tar tid på sig att dra slutsatser.", modifiers: [{type: 'attribute', amount: '-2', target: 'Psyke' }] },
  { min: 39, max: 40, description: "Kort. Rollpersonen är ovanligt kort." , modifiers: [{type: 'attribute', amount: '-1', target: 'Styrka' }] },
  { min: 41, max: 41, description: "Kraftig hårväxt. Rollpersonen är myckte kraftigt behårad över hela kroppen.", modifiers: [{type: 'attribute', amount: '-2', target: 'Personlighet' }] },
  { min: 42, max: 42, description: "Känslig för infektioner och smittoämnen." , modifiers: [{type: 'attribute', amount: '-2', target: 'Tålighet' }] },
  { min: 43, max: 44, description: "Lugndefekt: Minskad syreupptagningsförmåga innebär att rollpersonens utmattningskolumner minskar med två." },
  { min: 45, max: 45, description: "Läspar kraftigt: Rollpersonen har svårt med sociala färdigheter och får en nivå (+Ob1T6) svårare om det innebär tal." },
  { min: 46, max: 47, description: "Lättpåverkad: Rollpersonen har svårt att säga nej till andra.",  modifiers: [{type: 'attribute', amount: '-2', target: 'Vilja' }] },
  { min: 48, max: 49, description: "Mager: Rollpersonen är mycket smal vilket påverkar styrka och hälsa negativt. Kroppsbyggnad minskar ett steg (dock aldrig under Klen).", modifiers: [{type: 'attribute', amount: '-2', target: 'Tålighet' }] },
  { min: 50, max: 54, description: "Manisk: Rollpersonen är besatt av något specifikt, som pengar, sex eller odling. För att kunna ägna sig åt annat krävs ett lätt slag (Ob2T6) mot PSY." },
  { min: 55, max: 55, description: "Migrän: Rollpersonen lider av kraftig migrän. Varje gång rollpersonen vaknar efter en sömnperiod får rollpersonen Ob1T6-1 poäng smärta." },
  { min: 56, max: 56, description: "Missbildad höft: En skada som påverkar rörelseförmågan negativt. Rollpersonens förflyttning minskar med 2." },
  { min: 57, max: 58, description: "Muskeldefekt: Rollpersonen är svag.",  modifiers: [{type: 'attribute', amount: '-2', target: 'Styrka' }] },
  { min: 59, max: 59, description: "Nervöst lagd: Minska analet psykoskolumner med två (lägst 1)." },
  { min: 60, max: 61, description: "Obildad: Rollpersonen hade svårt att lära sig saker som ung.",  modifiers: [{type: 'attribute', amount: '-2', target: 'Bildning' }] },
  { min: 62, max: 62, description: "Olyckskorp: Rollpersonen har otur i alla tänkbara situationer.",  modifiers: [{type: 'attribute', amount: '-2', target: 'Tur' }] },
  { min: 63, max: 63, description: "Ordblind: Rollpersonen kan inte öka Skriva/läsa högre än 5." },
  { min: 64, max: 64, description: "Relativt ofarlig permanent sjukdom som psoriasis. Ses som hinder av intoleranta människor." },
  { min: 65, max: 65, description: "Reumatisk: Rollpersonen har ont i lederna och svårt att röra sig.", modifiers: [{type: 'attribute', amount: '-2', target: 'Rörlighet' }] },
  { min: 66, max: 66, description: "Sifferblind: Kan inte räkna eller tolka siffror lätt. Matematik och Programmering kan maximalt höjas till nivå 5." },
  { min: 67, max: 67, description: "Skakningar: Får spasmattacker vid stressade situationer, exempelvis strid. Måste då slå ett lätt slag mot TÅL för att inte få ett anfall som gör alla handlingar en nivå svårare under en minuts tid." },
  { min: 68, max: 68, description: "Skallig: Har mycket tunt hår eller inget alls, får ofta dåligt humör p.g.a. solen." },
  { min: 69, max: 70, description: "Skrikig röst: Får sociala svårigheter (+ObT16) vid situationer där hen uttrycker sig verbalt." },
  { min: 71, max: 72, description: "Smutsig mun: Rollpersonen svär extremt mycket." },
  { min: 73, max: 73, description: "Smärtkänslig: Minska antalet kolumner för Smärta med två (-2)." },
  { min: 74, max: 74, description: "Stammar: Får sociala svårigheter (+ObT16) i situationer där hen uttrycker sig verbalt." },
  { min: 75, max: 76, description: "Steril: Kan aldrig få barn." },
  { min: 77, max: 77, description: "Stor mage: Ökad vikt (ObT16+10) kg.", modifiers: [{type: 'attribute', amount: '-2', target: 'Rörlighet' }]},
  { min: 78, max: 78, description: "Stressbenägen: Varje gång rollpersonen får psykoskryss får rollpersonen ett extra psykoskryss." },
  { min: 79, max: 79, description: "Stridspanik: Presterar alltid dåligt i strid. Rollpersonens turordning halveras alltid." },
  { min: 80, max: 81, description: "Svag för det motsatta könet: Två nivåer svårare att övertala en person av motsatt kön." },
  { min: 82, max: 82, description: "Svag språkförmåga: Rollpersonen kan som högst ha Färdighetsnivå 10 i sitt modersmål och maximalt 5 i främmande språk." },
  { min: 83, max: 84, description: "Svettningar: Rollpersonen har kraftiga svettning vilket ger två nivåer svårare på Förföra, utom då rollpersonen befinner sig i vatten." },
  { min: 85, max: 85, description: "Synfel: Halvera rollpersonens SYN." },
  { min: 86, max: 86, description: "Tidigare mentalsjuk: Alla slag mot mentalvärdet är en nivå svårare (+Ob1T6)." },
  { min: 87, max: 87, description: "Trög. Rollpersonen har en nivå svårare när det gäller att agera snabbt, t.ex. alla handlingar i första stridsrundan." },
  { min: 88, max: 89, description: "Tystlåten: Säger sällan mer än ett fåtal ord." },
  { min: 90, max: 91, description: "Tål ej alkohol: Blir snabbt stupfull även av små mängder. Alla slag mot Supa blir två nivåer svårare (+Ob2T6)." },
  { min: 92, max: 93, description: "Udda sexuell läggning: Ses som avvikande och väcker misstänksamhet i vissa miljöer." },
  { min: 94, max: 94, description: "Uselt nattsyn: En nivå svårare på alla slag mot SYN vid dåliga ljusförhållanden." },
  { min: 95, max: 95, description: "Utslag. Rollpersonen har stora röda utslag över hela kroppen. Ej farliga, men i alla sociala situationer där rollpersonen inte döljer dessa för hen en nivå svårare på alla färdigheter (+Ob1T6)." },
  { min: 96, max: 96, description: "Vanställt ansikte: Fram till att rollpersonen har övertygat dem att hen innerst inne är snäll får rollpersonen en nivå svårare på alla sociala färdigheter." },
  { min: 97, max: 97, description: "Viskande röst: Rollpersonen kan inte skrika på grund av sina stämband och hörs maximalt fem meter bort." },
  { min: 98, max: 98, description: "Ärrad och dålig hy: Rollpersonen har alltid en nivå svårare på Förföra." },
  { min: 99, max: 100, description: "Slå två gånger på denna tabell och använd båda resultaten." },
]


const upbringingEvents = [
 {
    min: 1,
    max: 5,
    event: "Born into a noble family, comfortable upbringing.",
    // No modifiers for this event
  },
  {
    min: 6,
    max: 15,
    event: "Grew up in a bustling merchant town, learned about trade.",
    // Example: This event increases Bildning (Education)
    modifiers: [
      { type: 'attribute', target: 'Bildning', amount: 1 },
      // You could add other types of modifiers here too, e.g.,
      // { type: 'skill', target: 'Trade', amount: 5 },
      // { type: 'inventory', item: { name: 'Small Coin Pouch', quantity: 1 } }
    ]
  },
  {
    min: 16,
    max: 25,
    event: "Lived in a quiet farming village, close-knit community.",
  },
  {
    min: 26,
    max: 35,
    event: "Orphaned early, learned to survive on the streets.",
    modifiers: [
      { type: 'attribute', target: 'Rörlighet', amount: 2 }, // Agility
      { type: 'attribute', target: 'Tålighet', amount: 1 }, // Toughness
    ]
  },
  {
    min: 36,
    max: 45,
    event: "Raised by a reclusive sage, gained unusual knowledge.",
    modifiers: [
      { type: 'attribute', target: 'Psyke', amount: 2 }, // Psyche
      { type: 'attribute', target: 'Vilja', amount: 1 }, // Willpower
    ]
  },
  {
    min: 46,
    max: 55,
    event: "Childhood spent in a military camp, disciplined and tough.",
    modifiers: [
      { type: 'attribute', target: 'Styrka', amount: 2 }, // Strength
      { type: 'attribute', target: 'Tålighet', amount: 1 }, // Toughness
    ]
  },
  {
    min: 56,
    max: 65,
    event: "Survived a major natural disaster (flood, fire, earthquake).",
    modifiers: [
      { type: 'attribute', target: 'Tålighet', amount: 2 },
      { type: 'attribute', target: 'Psyke', amount: -1 }, // Could also be negative!
    ]
  },
  {
    min: 66,
    max: 75,
    event: "Encountered a magical creature, leaving a lasting impression.",
    modifiers: [
      { type: 'attribute', target: 'Syn', amount: 1 }, // Sight
    ]
  },
  {
    min: 76,
    max: 85,
    event: "Witnessed a significant historical event (battle, royal wedding).",
  },
  {
    min: 86,
    max: 95,
    event: "Had a loving and supportive family, generally happy."
  },
  {
    min: 96,
    max: 100,
    event: "Experienced a profound personal loss, shaping your worldview.",
    modifiers: [
      { type: 'attribute', target: 'Vilja', amount: 2 },
      { type: 'attribute', target: 'Personlighet', amount: -1 },
    ]
  },
]

export default upbringingEvents;
